Repository devhex314/algorithm-rs, pull requests merged in 2022-10, with the labels that each got.

#2 added binary search
  src/lib.rs
  src/main.rs
  src/search/binary_search.rs
  src/search/mod.rs
  src/sorting.rs
  src/sorting/mod.rs
Labels: hacktoberfest-accepted

#20 Adding merge sort algorithm in rust
  src/sorting/merge-sort.rs
Labels: hacktoberfest-accepted, hacktoberfest

#21 Adding radix sort algorithm in rust
  src/sorting/radix-sort.rs
Labels: hacktoberfest-accepted, hacktoberfest

#22 Adding shell sort algorithm in rust
  src/sorting/shell-sort.rs
Labels: hacktoberfest-accepted, hacktoberfest

#24 Adding Tim sort algorithm in Rust
  src/sorting/tim-sort.rs
Labels: hacktoberfest

#25 Adding pancake sorting algorithm in rust
  src/sorting/pancake-sort.rs
Labels: hacktoberfest

#29 dijkstra Algorithm
  src/Graphs/Dijkstra.rs
Labels: hacktoberfest-accepted, hacktoberfest
